config/routes.rb
F5m::Application.routes.draw do
  
  root :to => 'bip_configs#index'
    

  resources :contacts

  resources :bip_configs do
    resources :bipselfips
    resources :virtuals do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipprofiles do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipclasses do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipmonitors do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bippools do
        put 'migrate'
        put 'unmigrate'
      end
    resources :biprules do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipnodes do
        put 'migrate'
        put 'unmigrate'
      end
  end
  
  match 'bip_configs/upload' => 'bip_configs#upload'

end

app/models/bip_config.rb
class BipConfig < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :virtuals,           :dependent => :destroy
  has_many :bippools,           :dependent => :destroy
  has_many :bipprofiles,        :dependent => :destroy
  has_many :bipnodes,           :dependent => :destroy
  has_many :bipmonitors,        :dependent => :destroy
  has_many :bipmembers,         :dependent => :destroy
  has_many :bipselfips,         :dependent => :destroy
  has_many :bipclasses,         :dependent => :destroy
  has_many :biprules,           :dependent => :destroy
  has_many :bipprofilevirtuals, :dependent => :destroy
  has_many :bippoolmonitors,    :dependent => :destroy
  has_many :bippoolvirtuals,    :dependent => :destroy
  has_many :virtualrules,       :dependent => :destroy
end

app/controllers/bip_configs_controller.rb
class BipConfigsController < ApplicationController
  layout :resolve_layout
  
  # GET /bip_configs
  # GET /bip_configs.xml
  def index
    @bip_configs = BipConfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bip_configs }
    end
  end

  # GET /bip_configs/1
  # GET /bip_configs/1.xml
  def show
    @bip_config = BipConfig.find(params[:id])
    
    @bipcount = Hash.new
    @bipcount[:virtuals]    = @bip_config.virtuals.count
    @bipcount[:bipselfips]  = @bip_config.bipselfips.count
    @bipcount[:bippools]    = @bip_config.bippools.count
    @bipcount[:bipmonitors] = @bip_config.bipmonitors.count
    @bipcount[:bipnodes]    = @bip_config.bipnodes.count
    @bipcount[:biprules]    = @bip_config.biprules.count
    @bipcount[:bipclasses]  = @bip_config.bipclasses.count
    @bipcount[:bipprofiles] = @bip_config.bipprofiles.count 
    @bipcount[:virtuals_migrated]     = @bip_config.virtuals.find_all_by_migrated(true).count  
    @bipcount[:bippools_migrated]     = @bip_config.bippools.find_all_by_migrated(true).count    
    @bipcount[:bipmonitors_migrated]  = @bip_config.bipmonitors.find_all_by_migrated(true).count    
    @bipcount[:bipnodes_migrated]     = @bip_config.bipnodes.find_all_by_migrated(true).count    
    @bipcount[:biprules_migrated]     = @bip_config.biprules.find_all_by_migrated(true).count    
    @bipcount[:bipclasses_migrated]   = @bip_config.bipclasses.find_all_by_migrated(true).count    
    @bipcount[:bipprofiles_migrated]  = @bip_config.bipprofiles.find_all_by_migrated(true).count    
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bip_config }
    end
  end

  # GET /bip_configs/new
  # GET /bip_configs/new.xml
  def new
    @bip_configs = BipConfig.all
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bip_config }
    end
  end

  def upload     
    file_param = params[:upload][:file]
    filedata = file_param.read
    
    conf_name = params[:upload][:name]
      
    @data = BipConfig.create(:name => conf_name, :content => filedata)
    
    parse_selfips(filedata).each do |n,c|
      Bipselfip.create( :name => n, :content => c[:full], :bip_config_id => @data.id, 
                        :netmask => c[:netmask], :unit => c[:unit], :floating => c[:floating], :vlan => c[:vlan])
    end  
    
    parse_profiles(filedata).each do |n,c|
      Bipprofile.create(:name => n, :bip_config_id => @data.id, :ptype => c[:type], :content => c[:full], :migrated => false )
    end
    
    parse_rules(filedata).each do |n,c|
      Biprule.create(:name => n, :content => c, :bip_config_id => @data.id, :migrated => false)
    end
    
    parse_monitors(filedata).each do |n,c|
      Bipmonitor.create(:name => n, :content => c, :bip_config_id => @data.id, :migrated => false)
    end
    
    parse_classes(filedata).each do |n,c|
      Bipclass.create(:name => n, :content => c, :bip_config_id => @data.id, :migrated => false)
    end
    
    parse_nodes(filedata).each do |n,c|
      Bipnode.create( :name => n, :content => c[:full], :bip_config_id => @data.id, :dyn_ratio => c[:dyn_ratio], 
                      :limit => c[:limit], :monitor => c[:monitor], :ratio => c[:ratio], :screen => c[:screen], 
                      :updown => c[:updown], :migrated => false)
    end
    
    parse_pools(filedata).each do |n,c|
      bippool = Bippool.create(:name => n, :content => c[:full], :bip_config_id => @data.id,
                      :lbmethod => c[:lb_method], :members => c[:members].join(','), :monitors => c[:monitors].join(','),
                      :migrated => false)
                      
      c[:members].each do |m|        
        mem = m.split(':')
        node = Bipnode.find_or_create_by_name_and_bip_config_id(mem[0], @data.id)
        member = Bipmember.find_or_create_by_name_and_bip_config_id(:name => m, :bip_config_id => @data.id, :ip => mem[0],
                                                                    :port => mem[1], :bipnode_id => node.id, :bippool_id => bippool.id,
                                                                    :migrated => false)

        logger.debug "DEBUG POOL Members from pool. node: " + mem[0] + ' port: ' + mem[1]
      end
            
      c[:monitors].each do |m|
        monitor = Bipmonitor.find_or_create_by_name_and_bip_config_id(m, @data.id)
        poolmon = Bippoolmonitor.create(:bippool_id => bippool.id, :bipmonitor_id => monitor.id, :bip_config_id => @data.id)
        
        logger.debug "DEBUG POOL Monitor: " + m
      end
      
    end

    parse_virtuals(filedata).each do |n,c|
      virtual = Virtual.create(:name => n, :content => c[:full], :bip_config_id => @data.id, :enable => c[:enable], :destination => c[:destination],
                      :mask => c[:mask], :mirror => c[:mirror], :limit => c[:limit], :ip_protocol => c[:ip_protocol], :snat => c[:snat],
                      :snatpool => c[:snatpool], :srcport => c[:srcport], :type => c[:type], :pool => c[:pool], :persist => c[:persist],
                      :fb_persist => c[:fb_persist], :profiles => c[:profiles], :rules => c[:rules], :vlans => c[:vlans],
                      :httpclasses => c[:httpclasses], :migrated => false)
                      
      bippool = Bippool.find_or_create_by_name_and_bip_config_id(c[:pool], @data.id) unless c[:pool].nil?
      poolvirtual = Bippoolvirtual.create(:bippool_id => bippool.id, :virtual_id => virtual.id, :bip_config_id => @data.id ) unless c[:pool].nil?
      
      c[:rules].each do |r|
        rule = Biprule.find_or_create_by_name_and_bip_config_id(r, @data.id)
        virtualrule = Virtualrule.create(:virtual_id => virtual.id, :biprule_id => rule.id, :bip_config_id => @data.id )
      end
      
      c[:profiles].each do |p|
        profile = Bipprofile.find_or_create_by_name_and_bip_config_id(p, @data.id) unless c[:profiles].nil?
        bipprofilevirtual = Bipprofilevirtual.create(:virtual_id => virtual.id, :bipprofile_id => profile.id, :bip_config_id => @data.id) unless c[:profiles].nil?
      end
      
    end
    
    redirect_to bip_configs_path, :notice => conf_name + ' was successfully created.'
  end

  # DELETE /bip_configs/1
  # DELETE /bip_configs/1.xml
  def destroy
    @bip_config = BipConfig.find(params[:id])
    @bip_config.destroy

    respond_to do |format|
      format.html { redirect_to(bip_configs_url, :alert => @bip_config.name + " successfully destroyed.") }
      format.xml  { head :ok }
    end
  end
  
  private

    def resolve_layout
#      case action_name
#      when "new", "upload"
#        "new_bip_config"
#      else
        "application"
#      end
    end
  
end

app/helpers/bip_configs_helper.rb
module BipConfigsHelper
end

app/views/bip_configs/_form.html.erb
<h2>Upload a BigIP Config file:</h2>
<div class="span12">
	<%= form_for :upload, :url => { :action => :upload }, :html => { :multipart => true } do |f| %>
		<fieldset>
			<div class="clearfix">
				<%= f.label :name %>
				<div class="input">
			    	<%= f.text_field :name %>
			  	</div>
			</div>
			<div class="clearfix">
				<%= f.label :file %>
				<div class="input">
			    	<%= f.file_field :file %>
			  	</div>
			</div>
						
		</fieldset>
		<div class="clearfix">
			<div class="input">
		    	<%= f.submit "Upload", :class => "btn primary" %> <%= link_to "Cancel", bip_configs_path, :class => "btn" %>
			</div>
		</div>
	<% end %>
</div>

app/views/bip_configs/_topheader.html.erb
<% if @bip_config.nil? or @bip_config.name.nil? %>

	<%= link_to "BigIP Config Parser", bip_configs_path, :class =>"brand" %>
	<ul class="nav">
		<li><%= link_to "Home", 	bip_configs_path %></li>
		<li><%= link_to "Contacts",	contacts_path %></li>
		<li><%= link_to 'Upload', new_bip_config_path, :class => "pull-right" %></li>			
	</ul>

<% else %>

	<%= link_to "BigIP Config Parser: " + @bip_config.name, bip_config_path(@bip_config), :class =>"brand" %>
	<ul class="nav">
		<li><%= link_to "Home", 	bip_configs_path %></li>
		<li><%= link_to "Virtuals", [@bip_config, :virtuals ]	%></li>
		<li><%= link_to "Profiles",	[@bip_config, :bipprofiles ]%></li>
		<li><%= link_to "Rules", 	[@bip_config, :biprules ]	%></li>
		<li><%= link_to "Classes", 	[@bip_config, :bipclasses ]	%></li>
		<li><%= link_to "Pools", 	[@bip_config, :bippools ]	%></li>
		<li><%= link_to "Monitors", [@bip_config, :bipmonitors ]%></li>
		<li><%= link_to "Nodes", 	[@bip_config, :bipnodes ]	%></li>
		<li><%= link_to "SelfIps", 	[@bip_config, :bipselfips]	%></li>
		<li><%= link_to "Contacts",	contacts_path %></li>
		<li><%= link_to 'Upload', new_bip_config_path %></li>
	</ul>

<% end %>

app/views/bip_configs/index.html.erb
<table class="span10">
	<thead>
		<tr>
		    <th>Name</th>
		    <th></th>
		    <th></th>
		</tr>
	</thead>
	<tbody>
		<% @bip_configs.each do |bip_config| %>
		  <tr>
		    <td><%= bip_config.name %></td>
		    <td><%= link_to 'Show', bip_config, :class => "btn info" %></td>
		    <td><%= link_to 'Destroy', bip_config, :class => "btn danger",  :confirm => 'Are you sure?', :method => :delete %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/bip_configs/new.html.erb
<%= render 'form' %>

app/views/bip_configs/show.html.erb
<table>
	<thead>
		<tr>
		<td></td>
			<td><%= link_to "Virtuals", [@bip_config, :virtuals ]	%></td>
			<td><%= link_to "Profiles",	[@bip_config, :bipprofiles ]%></td>
			<td><%= link_to "Rules", 	[@bip_config, :biprules ]	%></td>
			<td><%= link_to "Classes", 	[@bip_config, :bipclasses ]	%></td>
			<td><%= link_to "Pools", 	[@bip_config, :bippools ]	%></td>
			<td><%= link_to "Monitors", [@bip_config, :bipmonitors ]%></td>
			<td><%= link_to "Nodes", 	[@bip_config, :bipnodes ]	%></td>
			<td><%= link_to "SelfIps", 	[@bip_config, :bipselfips]	%></td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Total</td>
			<td>(<%= @bipcount[:virtuals] 	%>)</td>
			<td>(<%= @bipcount[:bipprofiles] 	%>)</td>
			<td>(<%= @bipcount[:biprules] 	%>)</td>
			<td>(<%= @bipcount[:bipclasses] 	%>)</td>
			<td>(<%= @bipcount[:bippools] 	%>)</td>
			<td>(<%= @bipcount[:bipmonitors] %>)</td>
			<td>(<%= @bipcount[:bipnodes]	%>)</td>
			<td>(<%= @bipcount[:bipselfips] 	%>)</td>
		</tr>
		<tr>
			<td>Migrated</td>
			<td>(<%= @bipcount[:virtuals_migrated] 	%>)</td>
			<td>(<%= @bipcount[:bipprofiles_migrated] 	%>)</td>
			<td>(<%= @bipcount[:biprules_migrated] 	%>)</td>
			<td>(<%= @bipcount[:bipclasses_migrated] %>)</td>
			<td>(<%= @bipcount[:bippools_migrated] 	%>)</td>
			<td>(<%= @bipcount[:bipmonitors_migrated] %>)</td>
			<td>(<%= @bipcount[:bipnodes_migrated]	%>)</td>
			<td>(N/A)</td>
		</tr>
		<tr>
			<td>UnMigrated</td>
			<td>(<%= @bipcount[:virtuals] - @bipcount[:virtuals_migrated] %>)</td>
			<td>(<%= @bipcount[:bipprofiles] - @bipcount[:bipprofiles_migrated]	%>)</td>
			<td>(<%= @bipcount[:biprules] - @bipcount[:biprules_migrated] %>)</td>
			<td>(<%= @bipcount[:bipclasses] - @bipcount[:bipclasses_migrated] %>)</td>
			<td>(<%= @bipcount[:bippools] - @bipcount[:bippools_migrated] %>)</td>
			<td>(<%= @bipcount[:bipmonitors] - @bipcount[:bipmonitors_migrated] %>)</td>
			<td>(<%= @bipcount[:bipnodes] - @bipcount[:bipnodes_migrated] %>)</td>
			<td>(N/A)</td>
		</tr>
	</tbody>
</table>