config/routes.rb
F5m::Application.routes.draw do
  
  root :to => 'bip_configs#index'
    

  resources :contacts

  resources :bip_configs do
    resources :bipselfips
    resources :virtuals do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipprofiles do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipclasses do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipmonitors do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bippools do
        put 'migrate'
        put 'unmigrate'
      end
    resources :biprules do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipnodes do
        put 'migrate'
        put 'unmigrate'
      end
  end
  
  match 'bip_configs/upload' => 'bip_configs#upload'

end

app/models/bip_config.rb
class BipConfig < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :virtuals,           :dependent => :destroy
  has_many :bippools,           :dependent => :destroy
  has_many :bipprofiles,        :dependent => :destroy
  has_many :bipnodes,           :dependent => :destroy
  has_many :bipmonitors,        :dependent => :destroy
  has_many :bipmembers,         :dependent => :destroy
  has_many :bipselfips,         :dependent => :destroy
  has_many :bipclasses,         :dependent => :destroy
  has_many :biprules,           :dependent => :destroy
  has_many :bipprofilevirtuals, :dependent => :destroy
  has_many :bippoolmonitors,    :dependent => :destroy
  has_many :bippoolvirtuals,    :dependent => :destroy
  has_many :virtualrules,       :dependent => :destroy
end

app/models/bipclass.rb
class Bipclass < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
end

app/models/bipmember.rb
class Bipmember < ActiveRecord::Base
  belongs_to :bippool
  belongs_to :bipnode
end

app/models/bipmonitor.rb
class Bipmonitor < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :bippoolmonitors
  has_many :bippools, :through =>:bippoolmonitors
end

app/models/bipnode.rb
class Bipnode < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :bipmembers
  has_many :bippools, :through => :bipmembers
end

app/models/bippool.rb
class Bippool < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :bipmembers
  has_many :bipnodes, :through => :bipmembers
  has_many :bippoolmonitors
  has_many :bipmonitors, :through => :bippoolmonitors
  has_many :virtuals, :through => :bippoolvirtuals
  has_many :bippoolvirtuals
end
  

app/models/bippoolmonitor.rb
class Bippoolmonitor < ActiveRecord::Base
  belongs_to :bippool
  belongs_to :bipmonitor
end

app/models/bippoolvirtual.rb
class Bippoolvirtual < ActiveRecord::Base
  belongs_to :bippool
  belongs_to :virtual
end

app/models/bipprofile.rb
class Bipprofile < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :virtuals, :through => :bipprofilevirtuals
  has_many :bipprofilevirtuals
end

app/models/bipprofilevirtual.rb
class Bipprofilevirtual < ActiveRecord::Base
  belongs_to :bipprofile
  belongs_to :virtual
end

app/models/biprule.rb
class Biprule < ActiveRecord::Base
  validates :name, :presence => true
  has_many :virtuals, :through => :virtualrules
  belongs_to :bip_config
end

app/models/bipselfip.rb
class Bipselfip < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
  has_many :virtuals
  
  def contact_name
    "#{name}"
  end
  
end

app/models/virtual.rb
class Virtual < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  belongs_to :contact
  has_many :bippools, :through => :bippoolvirtuals
  has_many :biprules, :through => :virtualrules
  has_many :bipprofiles, :through => :bipprofilevirtuals
  has_many :virtualrules
  has_many :bippoolvirtuals
  has_many :bipprofilevirtuals
end

app/models/virtualrule.rb
class Virtualrule < ActiveRecord::Base
  belongs_to :virtual
  belongs_to :biprule
end

app/controllers/bippools_controller.rb
class BippoolsController < ApplicationController

  def index
    @bip_config = BipConfig.find(params[:bip_config_id])
    @bippools = @bip_config.bippools.all

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def show
    @bip_config = BipConfig.find(params[:bip_config_id])
    @bippool = @bip_config.bippools.find(params[:id])
    #@bipnodes = @bippool.bipnodes.all
  end

  def update
    @bip_config = BipConfig.find(params[:bip_config_id])
    @bippool = @bip_config.bippools.find(params[:id])
    @bippool.update_attributes(params[:bippool])
  end
  
  def migrate
    @bip_config = BipConfig.find(params[:bip_config_id])
    @bippool = @bip_config.bippools.find(params[:bippool_id])
    @bippool.update_attributes(:migrated => true)
  end
  
  def unmigrate
    @bip_config = BipConfig.find(params[:bip_config_id])
    @bippool = @bip_config.bippools.find(params[:bippool_id])
    @bippool.update_attributes(:migrated => false)
  end
  
end

app/helpers/bipclasses_helper.rb
module BipclassesHelper
end

app/helpers/bipnodes_helper.rb
module BipnodesHelper
end

app/helpers/bippools_helper.rb
module BippoolsHelper
end

app/helpers/biprules_helper.rb
module BiprulesHelper
end

app/helpers/bipselfips_helper.rb
module BipselfipsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/virtuals_helper.rb
module VirtualsHelper
end

app/views/bippools/_bippool.html.erb
<table class="zebra-striped">
	<thead>
		<tr>
			<th>Members</th>
			<th>Monitors</th>
			<th>Content</th>
			<th>Migrated</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<% @bippool.bipmembers.each do |m| %>
					<%= m.bipnode.name %>:<%= m.port %><br />
				<% end %>
			</td>
			<td>
				<% @bippool.bipmonitors.each do |m| %>
					<%= m.name %><br />
				<% end %>
			</td>
			<td><pre><%= @bippool.content %></pre></td>
			<td>
				<div class="migrated-image">
					<% if @bippool.migrated %>
						<%= image_tag "green-check.png", :width => 50, :height => 50 %>
					<% else %>
						<%= image_tag "red-x.png", :width => 50, :height => 50 %>
					<% end %>
				</div>
			</td>
		</tr>
	</tbody>
</table>

app/views/bippools/_members.html.erb
<% bip_pool.bipmembers.each do |m| %>
	<div class="modal hide fade" id="modal-window-<%= bip_pool.name + "-" + m.bipnode.name %>">
		<div class="modal-header">
			<h3><%= m.bipnode.name %></h3>
		</div>
		<div class="modal-body">
		</div>
	</div>
	<%= link_to m.bipnode.name, bip_config_bipnode_path(@bip_config.id, m.bipnode.id), 
				{:remote => true, 'data-controls-modal' =>  "modal-window-" + bip_pool.name + '-' + m.bipnode.name, 'data-backdrop' => true, 'data-keyboard' => true} %>:<%= m.port %><br />
<% end %>

app/views/bippools/_migrated.html.erb
<%= div_for(bip_pool, :class => "bip_migration_status") do %>
	<% if bip_pool.migrated %>
		<div class="bip_object_migrated">
		Migrated.<br />
		<%= link_to "Not Migrated?, (Click Here)", bip_config_bippool_unmigrate_path(@bip_config.id, bip_pool.id), 
									:method => :put, :remote => true %>
		</div>
	<% else %>
		<%= link_to "Mark Migrated", bip_config_bippool_migrate_path(@bip_config.id, bip_pool.id), 
								:method => :put, :remote => true %>
	<% end %>
<% end %>

app/views/bippools/_monitors.html.erb
<% bip_pool.bipmonitors.each do |m| %>
	<div class="modal hide fade" id="modal-window-<%= bip_pool.name + "-" + m.name %>">
		<div class="modal-header">
			<h3><%= m.name %></h3>
		</div>
		<div class="modal-body">
		</div>
	</div>
	<%= link_to m.name, bip_config_bipmonitor_path(@bip_config.id, m.id), 
				{:remote => true, 'data-controls-modal' =>  "modal-window-" + bip_pool.name + '-' + m.name, 'data-backdrop' => true, 'data-keyboard' => true} %><br />
<% end %>

app/views/bippools/index.html.erb
<h3>Bippools</h3>

<table class="zebra-striped">
	<thead>
		<tr>
			<th>Migrated</th>
			<th>Name</th>
			<th>Members</th>
			<th>Monitors</th>
		</tr>
	</thead>
	<tbody>
		<% @bippools.each do |bip_pool| %>
			<tr>
				<td><%= render :partial => "migrated", :locals => { :bip_pool => bip_pool } %></td>
				<td><%= bip_pool.name %><br /></td>
				<td><%= render :partial => "members", :locals => { :bip_pool => bip_pool } %></td>
				<td><%= render :partial => "monitors", :locals => { :bip_pool => bip_pool } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/bippools/migrate.js.erb
$('div#bippool_<%= @bippool.id %>').fadeOut(500,function(){ $(this).html('<%= escape_javascript(render(:partial => "migrated", :locals => { :bip_pool => @bippool })) %>').fadeIn(500); });

app/views/bippools/show.js.erb
$('.modal-body').html('<%= escape_javascript(render :partial => @bippool) %>');

app/views/bippools/unmigrate.js.erb
$('div#bippool_<%= @bippool.id %>').fadeOut(500,function(){ $(this).html('<%= escape_javascript(render(:partial => "migrated", :locals => { :bip_pool => @bippool })) %>').fadeIn(500); });

app/views/bippools/update.js.erb
$('div#bippool_<%= @bippool.id %>').fadeOut(500,function(){ $(this).html('<%= escape_javascript(render(:partial => "migrated", :locals => { :bip_pool => @bippool })) %>').fadeIn(500); });