config/routes.rb
F5m::Application.routes.draw do
  
  root :to => 'bip_configs#index'
    

  resources :contacts

  resources :bip_configs do
    resources :bipselfips
    resources :virtuals do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipprofiles do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipclasses do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipmonitors do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bippools do
        put 'migrate'
        put 'unmigrate'
      end
    resources :biprules do
        put 'migrate'
        put 'unmigrate'
      end
    resources :bipnodes do
        put 'migrate'
        put 'unmigrate'
      end
  end
  
  match 'bip_configs/upload' => 'bip_configs#upload'

end

app/models/bip_config.rb
class BipConfig < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :virtuals,           :dependent => :destroy
  has_many :bippools,           :dependent => :destroy
  has_many :bipprofiles,        :dependent => :destroy
  has_many :bipnodes,           :dependent => :destroy
  has_many :bipmonitors,        :dependent => :destroy
  has_many :bipmembers,         :dependent => :destroy
  has_many :bipselfips,         :dependent => :destroy
  has_many :bipclasses,         :dependent => :destroy
  has_many :biprules,           :dependent => :destroy
  has_many :bipprofilevirtuals, :dependent => :destroy
  has_many :bippoolmonitors,    :dependent => :destroy
  has_many :bippoolvirtuals,    :dependent => :destroy
  has_many :virtualrules,       :dependent => :destroy
end

app/models/bipclass.rb
class Bipclass < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
end

app/models/bipmember.rb
class Bipmember < ActiveRecord::Base
  belongs_to :bippool
  belongs_to :bipnode
end

app/models/bipmonitor.rb
class Bipmonitor < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :bippoolmonitors
  has_many :bippools, :through =>:bippoolmonitors
end

app/models/bipnode.rb
class Bipnode < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :bipmembers
  has_many :bippools, :through => :bipmembers
end

app/models/bippool.rb
class Bippool < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :bipmembers
  has_many :bipnodes, :through => :bipmembers
  has_many :bippoolmonitors
  has_many :bipmonitors, :through => :bippoolmonitors
  has_many :virtuals, :through => :bippoolvirtuals
  has_many :bippoolvirtuals
end
  

app/models/bippoolmonitor.rb
class Bippoolmonitor < ActiveRecord::Base
  belongs_to :bippool
  belongs_to :bipmonitor
end

app/models/bippoolvirtual.rb
class Bippoolvirtual < ActiveRecord::Base
  belongs_to :bippool
  belongs_to :virtual
end

app/models/bipprofile.rb
class Bipprofile < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  has_many :virtuals, :through => :bipprofilevirtuals
  has_many :bipprofilevirtuals
end

app/models/bipprofilevirtual.rb
class Bipprofilevirtual < ActiveRecord::Base
  belongs_to :bipprofile
  belongs_to :virtual
end

app/models/biprule.rb
class Biprule < ActiveRecord::Base
  validates :name, :presence => true
  has_many :virtuals, :through => :virtualrules
  belongs_to :bip_config
end

app/models/bipselfip.rb
class Bipselfip < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
  has_many :virtuals
  
  def contact_name
    "#{name}"
  end
  
end

app/models/virtual.rb
class Virtual < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :bip_config
  belongs_to :contact
  has_many :bippools, :through => :bippoolvirtuals
  has_many :biprules, :through => :virtualrules
  has_many :bipprofiles, :through => :bipprofilevirtuals
  has_many :virtualrules
  has_many :bippoolvirtuals
  has_many :bipprofilevirtuals
end

app/models/virtualrule.rb
class Virtualrule < ActiveRecord::Base
  belongs_to :virtual
  belongs_to :biprule
end

app/controllers/biprules_controller.rb
class BiprulesController < ApplicationController

  def index
    @bip_config = BipConfig.find(params[:bip_config_id])
    @biprules = @bip_config.biprules.all

    #@biprules.each do |m|
    #  m.content = m.content.nil? ? ['parse error'] : m.content.strip.split(/\n/)
    #end
    #<td><%= render :partial => "content", :locals => { :bip_rule => bip_rule } %></td>

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def show
    @bip_config = BipConfig.find(params[:bip_config_id])
    @biprule = @bip_config.biprules.find(params[:id])
    #@bipmon = @bipmonitor.content.nil? ? ['monitorroot'] : @bipmonitor.content.strip.split(/\n/)
  end
  
  def update
    @bip_config = BipConfig.find(params[:bip_config_id])
    @biprule = @bip_config.biprules.find(params[:id])
    @biprule.update_attributes(params[:biprule])
  end

  def migrate
    @bip_config = BipConfig.find(params[:bip_config_id])
    @biprule = @bip_config.biprules.find(params[:biprule_id])
    @biprule.update_attributes(:migrated => true)
  end
  
  def unmigrate
    @bip_config = BipConfig.find(params[:bip_config_id])
    @biprule = @bip_config.biprules.find(params[:biprule_id])
    @biprule.update_attributes(:migrated => false)
  end
  
end

app/helpers/bipclasses_helper.rb
module BipclassesHelper
end

app/helpers/bipnodes_helper.rb
module BipnodesHelper
end

app/helpers/bippools_helper.rb
module BippoolsHelper
end

app/helpers/biprules_helper.rb
module BiprulesHelper
end

app/helpers/bipselfips_helper.rb
module BipselfipsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/virtuals_helper.rb
module VirtualsHelper
end

app/views/biprules/_biprule.html.erb
<table>
	<thead>
		<tr>
			<th>Content</th>
			<th>Migrated</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><pre><%= @biprule.content %></pre></td>
			<td>
				<div class="migrated-image">
					<% if @biprule.migrated %>
						<%= image_tag "green-check.png", :width => 50, :height => 50 %>
					<% else %>
						<%= image_tag "red-x.png", :width => 50, :height => 50  %>
					<% end %>
				</div>
			</td>
		</tr>
	</tbody>
</table>

app/views/biprules/_migrated.html.erb
<%= div_for(bip_rule, :class => "bip_migration_status") do %>
	<% if bip_rule.migrated %>
		<div class="bip_object_migrated">
		Migrated.<br />
		<%= link_to "Not Migrated?, (Click Here)", bip_config_biprule_unmigrate_path(@bip_config.id, bip_rule.id), 
									:method => :put, :remote => true %>
		</div>
	<% else %>
		<%= link_to "Mark Migrated", bip_config_biprule_migrate_path(@bip_config.id, bip_rule.id), 
								:method => :put, :remote => true %>
	<% end %>
<% end %>

app/views/biprules/index.html.erb
<h3>Biprules</h3>

<table class="zebra-striped">
	<thead>
		<tr>
			<th>Migrated</th>
			<th>Name</th>
			<th>Content</th>
		</tr>
	</thead>
	<tbody>
		<% @biprules.each do |bip_rule| %>
			<tr>
				<td><%= render :partial => "migrated", :locals => { :bip_rule => bip_rule } %></td>
				<td><%= bip_rule.name %></td>
				<td><pre><%= bip_rule.content %></pre></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/biprules/migrate.js.erb
$('div#biprule_<%= @biprule.id %>').fadeOut(500,function(){ $(this).html('<%= escape_javascript(render(:partial => "migrated", :locals => { :bip_rule => @biprule })) %>').fadeIn(500); });

app/views/biprules/show.js.erb
$('.modal-body').html('<%= escape_javascript(render :partial => @biprule) %>');

app/views/biprules/unmigrate.js.erb
$('div#biprule_<%= @biprule.id %>').fadeOut(500,function(){ $(this).html('<%= escape_javascript(render(:partial => "migrated", :locals => { :bip_rule => @biprule })) %>').fadeIn(500); });

app/views/biprules/update.js.erb
$('div#biprule_<%= @biprule.id %>').fadeOut(500,function(){ $(this).html('<%= escape_javascript(render(:partial => "migrated", :locals => { :bip_rule => @biprule })) %>').fadeIn(500); });